# General

set -g default-shell pwsh

## vi mode
set -g mode-keys vi
set -g focus-events on

## Scroll history
set -g history-limit 100000

## Show messages for 4 seconds
set -g display-time 4000

## Set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

## Make mouse useful
set -g mouse on

## Lower escape timing for quicker response to scroll-buffer access
set -g escape-time 0

## Disable command repeat
set -g repeat-time 0

# Windows

## PSReadLine inline predictions (may conflict with ConPTY)
set -g allow-predictions on

# Bell

set -g bell-action none
set -g visual-bell off

# Status bar

## Position
set -g status-position bottom

## Colours
set -g status-style "fg=colour67,bg=colour0"
set -g window-status-current-style "fg=colour75,bg=colour0,bold"
set -g pane-border-style "fg=colour242,bg=colour0"
set -g pane-active-border-style "fg=colour248,bg=colour0"

## Left
set -g status-left ""
set -g status-left-length 0

## Right
set -g status-right-length 64
set -g status-interval 2
set -g status-right "#[fg=colour67]#H  #[fg=colour75]%H:%M"

# Bindings

## Navigation
unbind s
bind s choose-tree -Z

## Resize shortcuts
bind -r < swap-window -t -1
bind -r > swap-window -t +1
unbind C-Left
unbind C-Right
unbind C-Up
unbind C-Down

## When creating a new window, use the current path
unbind c
bind c new-window -c "#{pane_current_path}"

## When creating a new pane, use the current path
bind "%" split-window -h -c "#{pane_current_path}"
bind '"'  split-window -v -c "#{pane_current_path}"

## Reload config shortcut
bind R source-file ~/.psmux.conf \; display "Config reloaded"

## Drag to re-order windows (doesn't work in psmux)
bind -n MouseDrag1Status swap-window -t=

## Double click on the window list to open a new window (doesn't work in psmux)
bind -n DoubleClick1Status new-window

## Pane navigation (tmux-sensible style)
bind C-p previous-window
bind C-n next-window
bind C-Up    select-pane -U
bind C-Down  select-pane -D
bind C-Left  select-pane -L
bind C-Right select-pane -R
